## Handling Imbalanced Dataset

1. Up Sampling
2. Down Sampling

In [9]:
import numpy as np
import pandas as pd

# Set the random seed for reproducibility
np.random.seed(123)

# Create a dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [10]:
n_class_0,n_class_1

(900, 100)

In [11]:
## CREATE MY DATAFRAME WITH IMBALANCED DATASET
class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

In [12]:
df=pd.concat([class_0,class_1]).reset_index(drop=True)

In [13]:
df

     feature_1  feature_2  target
0    -1.085631   0.551302       0
1     0.997345   0.419589       0
2     0.282978   1.815652       0
3    -1.506295  -0.252750       0
4    -0.578600  -0.292004       0
..         ...        ...     ...
995   1.376371   2.845701       1
996   2.239810   0.880077       1
997   1.131760   1.640703       1
998   2.902006   0.390305       1
999   2.697490   2.013570       1

[1000 rows x 3 columns]

In [14]:
df.tail()

     feature_1  feature_2  target
995   1.376371   2.845701       1
996   2.239810   0.880077       1
997   1.131760   1.640703       1
998   2.902006   0.390305       1
999   2.697490   2.013570       1

In [15]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [16]:
## upsampling
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [17]:
from sklearn.utils import resample
df_minority_upsampled=resample(df_minority,replace=True, #Sample With replacement
         n_samples=len(df_majority),
         random_state=42
        )

In [18]:
df_minority_upsampled.shape

(900, 3)

In [19]:
df_minority_upsampled.head()

     feature_1  feature_2  target
951   1.125854   1.843917       1
992   2.196570   1.397425       1
914   1.932170   2.998053       1
971   2.272825   3.034197       1
960   2.870056   1.550485       1

In [25]:
df_upsampled=pd.concat([df_majority,df_minority_upsampled])

In [26]:
df_upsampled

     feature_1  feature_2  target
0    -1.085631   0.551302       0
1     0.997345   0.419589       0
2     0.282978   1.815652       0
3    -1.506295  -0.252750       0
4    -0.578600  -0.292004       0
..         ...        ...     ...
952   1.188902   2.189189       1
965   3.919526   1.980541       1
976   2.810326   3.604614       1
942   3.621531   2.168229       1
974   1.160887   2.489203       1

[1800 rows x 3 columns]

In [21]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

## Down Sampling

In [22]:
import pandas as pd

# Set the random seed for reproducibility
np.random.seed(123)

# Create a dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

df = pd.concat([class_0, class_1]).reset_index(drop=True)

# Check the class distribution
print(df['target'].value_counts())

target
0    900
1    100
Name: count, dtype: int64

In [23]:
## downsampling
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [33]:
from sklearn.utils import resample
df_majority_downsampled=resample(df_majority,replace=True, #Sample With replacement
         n_samples=400,
         random_state=42
        )

In [34]:
df_majority_downsampled

     feature_1  feature_2  target
102   0.712265   0.718151       0
435   1.199988   0.574621       0
860   0.304515  -0.759475       0
270  -1.213385   0.675504       0
106   0.179549  -0.202659       0
..         ...        ...     ...
469   0.613068  -0.706136       0
374  -1.212269   0.351451       0
21    1.490732  -0.708322       0
749   1.256821  -0.629719       0
669   1.715469  -1.630497       0

[400 rows x 3 columns]

In [35]:
df_majority_downsampled['target'].value_counts()

target
0    400
Name: count, dtype: int64

In [36]:
df_newsample=pd.concat([df_majority_downsampled,df_minority_upsampled])

In [37]:
df_newsample

     feature_1  feature_2  target
102   0.712265   0.718151       0
435   1.199988   0.574621       0
860   0.304515  -0.759475       0
270  -1.213385   0.675504       0
106   0.179549  -0.202659       0
..         ...        ...     ...
952   1.188902   2.189189       1
965   3.919526   1.980541       1
976   2.810326   3.604614       1
942   3.621531   2.168229       1
974   1.160887   2.489203       1

[1300 rows x 3 columns]